version: "3.8"

services:
  music-bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/task
    working_dir: /var/task/
    depends_on:
      - mongo
    networks:
      - mongo-database
    entrypoint: ["poetry", "run"]
    command: ["python3", "main.py"]

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - mongo-database
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    networks:
      - mongo-database

networks:
  nginx-net:
    driver: bridge
  mongo-database:
    driver: bridge
